# Configuracao do DataSource
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Configuracao do Hibernate
spring.jpa.hibernate.ddl-auto=create-drop

# Configuracao da JPA - Habilita Log na execucao de SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuracao do H2 - Habilita Interface grafica no endpoint /h2-console
spring.h2.console.enabled=true